version: '3'
services:
  nginx:
    network_mode: "host"
    container_name: nginx
    volumes:
      - /data/log/nginx:/var/log/nginx
      - /data/cache/nginx:/var/cache/nginx
      - $PWD/sites-enabled:/etc/nginx/sites-enabled
      - /data/www/html:/etc/nginx/html
    image: nginx-overseas
